# Generated by Django 2.0 on 2018-06-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_auto_20180613_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
