# Generated by Django 2.0 on 2018-06-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180620_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='kirr_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click', to='shorten.KirrURL'),
        ),
    ]
