# Generated by Django 2.0 on 2018-06-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20180621_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='kirr_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorten.KirrURL'),
        ),
    ]
