# Generated by Django 2.0 on 2018-06-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0005_auto_20180613_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
